script: make

services:
  - docker

notifications:
  slack:
    secure: ZSz894BtDx+MY2m/pmqwPDd5WhYNs6Dz/CrjTJoQgaHvYQvIa5sMPxjybNvonKEkQ+50MTLqoRxCaTHq7M+s6afvq7rTSxC45bBQ3fT1HsEmsYo1aPsUwIQK/yJNSDuFJUYbcLuzeqppvInvzbZdoMNcImi32mqUzlTl5ifmGv0SU6SfctDQGxyP//dk5GVPIGZDquk0+/AXCfz1JZqyvFhQdfG9KqRKU/P37iRxtEmfiI3Il+TvHzwu7qmt+fW/2Zzh3X7Fa3Y4CUAsAAQX9l/iFe8bHjlxDg85dzv9OI6QfCcpUFzukdmKijWqhjqO9lXiy9zhYR1gQ7WjKAFL+n+ogjmWfAvePDQpiucwnv5RFGa+Q5dA7V52kW/5HCYQDLI/QjRWNfUtT+FL6C2hmVDdwLMMLYyFPsk0p06vuQXuKRKYXQCNus6GC/i9zQqEJdZ1Rqq00tINntlrdH7Vm3XXM+YiJu9lT37ZysoEN6F8dPBr6q4A3UbqowNaNlUSXUnxGQs+Fo77w7vx1eBREdU5ULtzOh1nZZhGcsGdQJcKhvettSzBEp3M0vELNu5e7N9Nz74dvvIb9vuYfJMKpBSs6ieLtZGOeVMabNxQnvSpV5jgBgfBRVgzRzVcUKQuHxN+EZwtRuiBZ2eITnxCRy3lEuC/Ns/y9p+Czv61+UA=
